### ISSUE TITLE
Buildcraft API decorating triggered by false positive, issuing a crash at load.

### ISSUE THREAD

**Issue by kane-thornwyrd** [cout970/Magneticraft-API-and-Issues#6] opened 2015-08-11 21:19 UTC
Hello,

First, thanks a lot for this really neat mod !

I experience a crash when I try to boot my modpack with Magneticraft.
I'll try to pinpoint it, but if you can help, that would be great !

Crash log: https://gist.github.com/kane-thornwyrd/ecea37cdba4f5f684588 .

My Modpack: under construction: http://www.curse.com/modpacks/Minecraft/233775-stranded-strained .

I try to get a Bioshock/Jurassic Park feel while highlighting mods that deserve a larger audience.

**Comment by kane-thornwyrd** [comment] 2015-08-12 06:19
Fun fact, I don't have Buildcraft...
```log
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
```

**Comment by kane-thornwyrd** [comment] 2015-08-12 06:21
Wait... WHAT ?!
```log
List of loaded APIs: 
[...]
		* BuildCraftAPI|core (1.0) from magneticraft-0.3.4.jar
		* BuildCraftAPI|fuels (2.0) from magneticraft-0.3.4.jar
		* BuildCraftAPI|gates (3.0) from magneticraft-0.3.4.jar
		* BuildCraftAPI|tools (1.0) from magneticraft-0.3.4.jar
		* BuildCraftAPI|transport (3.0) from magneticraft-0.3.4.jar
[...]
```

**Comment by kane-thornwyrd** [comment] 2015-08-12 06:46
So, as a workaround, I installed Buildcraft... It kinda solved the problem, except that I have Buildcraft now, and I don't want it.

My theory, as far as my understanding goes, is that at some point you decorate the Buildcraft API to do stuffs, it depend on the result of one or multiple tests, whom are triggered in a false positive way by another mod.

If I had access to your source I may help you find what test is suboptimal.

**Comment by kane-thornwyrd** [comment] 2015-08-12 07:48
BTW, I created an instance with only Magneticraft, Forge Multi Part and CodeChickenCore as a clean testbed, it worked flawlessly ! So I'm sure that the latest versions of Forge and those modules are not the origin of this issue.

**Comment by Cypher121** [comment] 2015-08-18 23:04
Duplicate of issue #1

**Comment by Cypher121** [comment] 2015-08-19 02:05
It seems to be a problem with DragonAPI

**Comment by kane-thornwyrd** [comment] 2015-08-20 09:01
That's right, it is the issue. I'm sorry, I'll fill another issue report because I crashed while asking for the recipe of a wood post.
It is maybe a bit too early to add Magneticraft, but I definitively keep you in my "mod to add later" list ! :/

**Closed** 2015-09-11 11:27 UTC
Labels: bug, compatibility issue, fixed for the next update
