### ISSUE TITLE
Shelving Unit with Mekanism Logistical Transport Crash

### ISSUE THREAD

**Issue by DeathStapler** [cout970/Magneticraft-API-and-Issues#82] opened 2016-02-19 16:21 UTC
When you place a Magneticraft Shelving Unit down next to an existing Mekanism Logistical Transporter pipe it causes a server crash.

Crash Report: http://pastebin.com/eSUqPnJm

**Comment by Cypher121** [comment] 2016-02-19 19:43
Duplicate of #77

**Closed by Cypher121** 2016-02-19 19:43 UTC

**Comment by DeathStapler** [comment] 2016-02-20 02:30
It sounds similar.  But, I'm able to duplicate this 100% of the time doing the same thing.  It was occurred in a modpack, then with only Mekanism and Magneticraft.

In Issue #77 it is mentioned that MechWarrior99 was unable to reproduce the bug.  Was that the case here also?

I'm not trying to be a nuisance, just trying to figure out the root cause of the problem.  

I would investigate it myself, but I'm not sure how to get mods setup in a development environment.
